name: Build and Deploy
on:
  push:
    branches:
      - main
env:
  VITE_APIKEY: ${{ secrets.VITE_APIKEY }}
  VITE_AUTHDOMAIN: ${{ secrets.VITE_AUTHDOMAIN }}
  VITE_DATABASEURL: ${{ secrets.VITE_DATABASEURL }}
  VITE_PROJECTID: ${{ secrets.VITE_PROJECTID }}
  VITE_STORAGEBUCKET: ${{ secrets.VITE_STORAGEBUCKET }}
  VITE_MESSAGINGSENDERID: ${{ secrets.VITE_MESSAGINGSENDERID }}
  VITE_APPID: ${{ secrets.VITE_APPID }}
  VITE_LOCATION_API_KEY: ${{ secrets.VITE_LOCATION_API_KEY }}
  VITE_LOCATION_API_URL: ${{ secrets.VITE_LOCATION_API_URL }}
permissions: 
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist # The folder the action should deploy.
